spring:
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/grid
    username: grid
    password: grid

application:
  security:
    jwt:
      secretKey: BQFXy4afcXCxKI7BNo8argHNwP5nh6AiCcSyLnkCs0xZkS8RPImDlK42uE4Mz/DmFEidO0ALl7Lkxs2s9aGwmw==
      expiration_time: 300000 # 5분
      refresh-token:
        expiration_time: 86400000 # 하루
  redis:
    host: localhost
    port: 6379
